In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import files
upload=files.upload()

Saving Global_Superstore2.csv to Global_Superstore2.csv

In [ ]:
global_df=pd.read_csv('Global_Superstore2.csv',encoding='latin-1')

In [ ]:
global_df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,City,State,...,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,32298,CA-2012-124891,31-07-2012,31-07-2012,Same Day,RH-19495,Rick Hansen,Consumer,New York City,New York,...,TEC-AC-10003033,Technology,Accessories,Plantronics CS510 - Over-the-Head monaural Wir...,2309.650,7,0.0,762.1845,933.57,Critical
1,26341,IN-2013-77878,05-02-2013,07-02-2013,Second Class,JR-16210,Justin Ritter,Corporate,Wollongong,New South Wales,...,FUR-CH-10003950,Furniture,Chairs,"Novimex Executive Leather Armchair, Black",3709.395,9,0.1,-288.7650,923.63,Critical
2,25330,IN-2013-71249,17-10-2013,18-10-2013,First Class,CR-12730,Craig Reiter,Consumer,Brisbane,Queensland,...,TEC-PH-10004664,Technology,Phones,"Nokia Smart Phone, with Caller ID",5175.171,9,0.1,919.9710,915.49,Medium
3,13524,ES-2013-1579342,28-01-2013,30-01-2013,First Class,KM-16375,Katherine Murray,Home Office,Berlin,Berlin,...,TEC-PH-10004583,Technology,Phones,"Motorola Smart Phone, Cordless",2892.510,5,0.1,-96.5400,910.16,Medium
4,47221,SG-2013-4320,05-11-2013,06-11-2013,Same Day,RH-9495,Rick Hansen,Consumer,Dakar,Dakar,...,TEC-SHA-10000501,Technology,Copiers,"Sharp Wireless Fax, High-Speed",2832.960,8,0.0,311.5200,903.04,Critical

In [ ]:
global_df.shape

(51290, 24)

In [ ]:
global_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 24 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Row ID          51290 non-null  int64
 1   Order ID        51290 non-null  object
 2   Order Date      51290 non-null  object
 3   Ship Date       51290 non-null  object
 4   Ship Mode       51290 non-null  object
 5   Customer ID     51290 non-null  object
 6   Customer Name   51290 non-null  object
 7   Segment         51290 non-null  object
 8   City            51290 non-null  object
 9   State           51290 non-null  object
 10  Country         51290 non-null  object
 11  Postal Code     9994 non-null   float64
 12  Market          51290 non-null  object
 13  Region          51290 non-null  object
 14  Product ID      51290 non-null  object
 15  Category        51290 non-null  object
 16  Sub-Category    51290 non-null  object
 17  Product Name    51290 non-null  object
 18  Sales           51290 non-null  float64
 19  Quantity        51290 non-null  int64
 20  Discount        51290 non-null  float64
 21  Profit          51290 non-null  float64
 22  Shipping Cost   51290 non-null  float64
 23  Order Priority  51290 non-null  object
dtypes: float64(5), int64(2), object(17)
memory usage: 9.4+ MB

In [ ]:
global_df.isnull().sum()

Row ID                0
Order ID              0
Order Date            0
Ship Date             0
Ship Mode             0
Customer ID           0
Customer Name         0
Segment               0
City                  0
State                 0
Country               0
Postal Code       41296
Market                0
Region                0
Product ID            0
Category              0
Sub-Category          0
Product Name          0
Sales                 0
Quantity              0
Discount              0
Profit                0
Shipping Cost         0
Order Priority        0
dtype: int64

In [ ]:
columns_needed = [
"Order ID",
"Order Date",
"Ship Date",
"Ship Mode",
"Customer ID",
"Segment",
"Country",
"City",
"State",
"Region",
"Product ID",
"Category",
"Sub-Category",
"Product Name",
"Sales",
"Quantity",
"Discount",
"Profit"
]

df = global_df[columns_needed]

In [ ]:
df["Order Date"]=pd.to_datetime(df["Order Date"])
df["Ship Date"]=pd.to_datetime(df["Ship Date"])

/tmp/ipykernel_216/2892683713.py:1: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["Order Date"]=pd.to_datetime(df["Order Date"])
/tmp/ipykernel_216/2892683713.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Order Date"]=pd.to_datetime(df["Order Date"])
/tmp/ipykernel_216/2892683713.py:2: UserWarning: Parsing dates in %d-%m-%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df["Ship Date"]=pd.to_datetime(df["Ship Date"])
/tmp/ipykernel_216/2892683713.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["Ship Date"]=pd.to_datetime(df["Ship Date"])

In [ ]:
df["shipping days"]=(df["Ship Date"]-df["Order Date"]).dt.days

/tmp/ipykernel_216/653366478.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["shipping days"]=(df["Ship Date"]-df["Order Date"]).dt.days

In [ ]:
df.to_csv("super_clean.csv",index=False)

In [ ]:
print(df.shape),
df['shipping days'].describe()

(51290, 19)

count    51290.000000
mean         3.969370
std          1.729437
min          0.000000
25%          3.000000
50%          4.000000
75%          5.000000
max          7.000000
Name: shipping days, dtype: float64

In [ ]:
import duckdb
con=duckdb.connect()
con.execute(""" CREATE TABLE superstore AS
SELECT * FROM read_csv_auto(super_clean.csv) """).fetchall()

[(51290,)]

In [ ]:
con.execute("SELECT count(*) FROM superstore").fetchall()

[(51290,)]

Total_sales

In [ ]:
con.execute(""" SELECT SUM(sales) FROM superstore """).fetchall()

[(12642501.909880515,)]

Total_profit

In [ ]:
con.execute(""" SELECT SUM(profit) FROM superstore """).fetchall()

[(1467457.2912799956,)]

Total count of orders

In [ ]:
con.execute(""" SELECT COUNT(DISTINCT "Order ID") FROM superstore""").fetchall()

[(25035,)]

Monthly sales trend

In [ ]:
con.execute("""
WITH monthly_sales AS(
SELECT DATE_TRUNC('month',"Order Date") AS order_month,
SUM(sales) AS current_month_sales
FROM superstore
GROUP BY 1)
SELECT order_month,
LAG(current_month_sales) OVER(ORDER BY order_month) AS previous_month_sales,
current_month_sales - LAG(current_month_sales) OVER(ORDER BY order_month) as revenue_growth
FROM monthly_sales
ORDER BY order_month
""").fetchall()

[(datetime.date(2011, 1, 1), None, None),
 (datetime.date(2011, 2, 1), 98898.48885999997, -7746.331879999867),
 (datetime.date(2011, 3, 1), 91152.1569800001, 54577.2103799999),
 (datetime.date(2011, 4, 1), 145729.36736, -28813.60318000008),
 (datetime.date(2011, 5, 1), 116915.76417999993, 29832.07192000012),
 (datetime.date(2011, 6, 1), 146747.83610000004, 68459.54412),
 (datetime.date(2011, 7, 1), 215207.38022000005, -99696.96109999997),
 (datetime.date(2011, 8, 1), 115510.41912000008, 92071.07209999963),
 (datetime.date(2011, 9, 1), 207581.4912199997, 82632.96412000057),
 (datetime.date(2011, 10, 1), 290214.4553400003, -91143.19129999986),
 (datetime.date(2011, 11, 1), 199071.26404000042, 99425.27347999965),
 (datetime.date(2011, 12, 1), 298496.53752000007, 35429.19707999984),
 (datetime.date(2012, 1, 1), 333925.7345999999, -198145.01435999988),
 (datetime.date(2012, 2, 1), 135780.72024000002, -35270.50326000003),
 (datetime.date(2012, 3, 1), 100510.21698, 62566.55418000027),
 (datetime.date(2012, 4, 1), 163076.77116000027, -2024.5016400004388),
 (datetime.date(2012, 5, 1), 161052.26951999983, 47312.62171999988),
 (datetime.date(2012, 6, 1), 208364.8912399997, 47810.80718000044),
 (datetime.date(2012, 7, 1), 256175.69842000015, -110938.9133000001),
 (datetime.date(2012, 8, 1), 145236.78512000004, 157906.15725999998),
 (datetime.date(2012, 9, 1), 303142.94238, -13753.776739998779),
 (datetime.date(2012, 10, 1), 289389.16564000124, -36449.31544000114),
 (datetime.date(2012, 11, 1), 252939.8502000001, 70572.56670000043),
 (datetime.date(2012, 12, 1), 323512.41690000053, 14744.549700000149),
 (datetime.date(2013, 1, 1), 338256.9666000007, -139071.0592200008),
 (datetime.date(2013, 2, 1), 199185.90737999987, -31946.25697999986),
 (datetime.date(2013, 3, 1), 167239.6504, 31354.379720000346),
 (datetime.date(2013, 4, 1), 198594.03012000036, -20772.71328000023),
 (datetime.date(2013, 5, 1), 177821.31684000013, 82677.24785999989),
 (datetime.date(2013, 6, 1), 260498.56470000002, 136021.04720000006),
 (datetime.date(2013, 7, 1), 396519.6119000001, -166590.65989999985),
 (datetime.date(2013, 8, 1), 229928.95200000022, 96559.83735999983),
 (datetime.date(2013, 9, 1), 326488.78936000005, 50130.456320000754),
 (datetime.date(2013, 10, 1), 376619.2456800008, -83212.60280000028),
 (datetime.date(2013, 11, 1), 293406.6428800005, 80582.71722000075),
 (datetime.date(2013, 12, 1), 373989.3601000013, 31465.017919998907),
 (datetime.date(2014, 1, 1), 405454.3780200002, -164185.82236000005),
 (datetime.date(2014, 2, 1), 241268.55566000013, -56431.20009999993),
 (datetime.date(2014, 3, 1), 184837.3555600002, 78263.4170600001),
 (datetime.date(2014, 4, 1), 263100.7726200003, -20328.91132000016),
 (datetime.date(2014, 5, 1), 242771.86130000014, 45629.184839999856),
 (datetime.date(2014, 6, 1), 288401.04614, 113413.01695999928),
 (datetime.date(2014, 7, 1), 401814.0630999993, -143108.38261999906),
 (datetime.date(2014, 8, 1), 258705.6804800002, 197914.26188000047),
 (datetime.date(2014, 9, 1), 456619.9423600007, 24537.30133999948),
 (datetime.date(2014, 10, 1), 481157.24370000017, -58390.614539999864),
 (datetime.date(2014, 11, 1), 422766.6291600003, 132512.3978399997),
 (datetime.date(2014, 12, 1), 555279.027, -52135.333519999636)]

Which product categories generate the highest sales?

In [ ]:
con.execute("""
SELECT category,SUM(sales) as total_sales
FROM superstore
GROUP BY 1
ORDER BY 2 DESC

""").fetchall()

[('Technology', 4744557.498080019),
 ('Furniture', 4110874.18629997),
 ('Office Supplies', 3787070.2254999117)]

Which region generates the most revenue?

In [ ]:
con.execute("""
SELECT region,SUM(sales),SUM(profit)
FROM  superstore
GROUP BY 1
ORDER BY 2 DESC

""").fetchall()

[('Central', 2822302.5199399963, 311403.98163999757),
 ('South', 1600907.040879991, 140355.76617999986),
 ('North', 1248165.6025199995, 194597.95252000084),
 ('Oceania', 1100184.6119999948, 120089.11200000021),
 ('Southeast Asia', 884423.1690000044, 17852.328999999965),
 ('North Asia', 848309.7809999981, 165578.42100000044),
 ('EMEA', 806161.3109999954, 43897.970999999954),
 ('Africa', 783773.2109999972, 88871.63099999996),
 ('Central Asia', 752826.5669999978, 132480.18700000033),
 ('West', 725457.8244999961, 108418.44890000028),
 ('East', 678781.2399999935, 91522.7800000001),
 ('Caribbean', 324280.86104000086, 34571.32104000004),
 ('Canada', 66928.16999999998, 17817.389999999992)]

Which categories are most profitable?

In [ ]:
con.execute("""
SELECT category,SUM(profit) AS total_profit
FROM superstore
GROUP BY 1
ORDER BY 2 DESC

""").fetchall()

[('Technology', 663778.7331799992),
 ('Office Supplies', 518473.83430000057),
 ('Furniture', 285204.72380000126)]

Which individual products generate the most revenue?

In [ ]:
con.execute("""
SELECT
"Product Name",SUM(sales) as total_sales
FROM superstore
GROUP BY 1
ORDER BY 2 DESC limit 10

""").fetchall()

[('Apple Smart Phone, Full Size', 86935.77860000002),
 ('Cisco Smart Phone, Full Size', 76441.53059999998),
 ('Motorola Smart Phone, Full Size', 73156.30300000001),
 ('Nokia Smart Phone, Full Size', 71904.55549999999),
 ('Canon imageCLASS 2200 Advanced Copier', 61599.824),
 ('Hon Executive Leather Armchair, Adjustable', 58193.48409999998),
 ('Office Star Executive Leather Armchair, Adjustable', 50661.684),
 ('Harbour Creations Executive Leather Armchair, Adjustable', 50121.516),
 ('Samsung Smart Phone, Cordless', 48653.46000000001),
 ('Nokia Smart Phone, with Caller ID', 47877.78570000001)]

Which shipping mode is fastest?

In [ ]:
con.execute("""
SELECT "Ship Mode",AVG("shipping days") as avg_shipping_days
FROM superstore
GROUP BY 1
ORDER BY 2 ASC LIMIT 1
""").fetchall()

[('Same Day', 0.03739355794150315)]

Which customer segment generates the most revenue?

In [ ]:
con.execute("""
SELECT segment,SUM(sales) as total_sales
 FROM superstore
 GROUP BY 1
 ORDER BY 2 DESC LIMIT 1

 """).fetchall()

[('Consumer', 6507949.417860084)]

Rank the top products by revenue within each category.

In [ ]:
con.execute("""
WITH product_revenue AS(
SELECT category,"Product Name",SUM(sales) AS total_sales,
RANK() OVER(PARTITION BY category ORDER BY SUM(sales) DESC) AS sales_rank
FROM superstore
GROUP BY 1,2
ORDER BY 1,3 DESC)
SELECT * FROM product_revenue WHERE sales_rank<=3  ORDER BY 3 desc
""").fetchall()

In [ ]:
df.to_csv("superglobal.csv",index=False)